//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnLTWHQT
{
    using System;
    using System.Collections.Generic;
    
    public partial class inbound_receipts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inbound_receipts()
        {
            this.inbound_receipt_details = new HashSet<inbound_receipt_details>();
        }
    
        public long id { get; set; }
        public string code { get; set; }
        public long supplier_id { get; set; }
        public long warehouse_id { get; set; }
        public System.DateTime received_at { get; set; }
        public string status { get; set; }
        public string notes { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public Nullable<decimal> total_amount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inbound_receipt_details> inbound_receipt_details { get; set; }
        public virtual supplier supplier { get; set; }
        public virtual user user { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}
