//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnLTWHQT
{
    using System;
    using System.Collections.Generic;
    
    public partial class inbound_receipt_details
    {
        public long receipt_id { get; set; }
        public long product_variant_id { get; set; }
        public int quantity { get; set; }
        public decimal input_price { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual inbound_receipts inbound_receipts { get; set; }
        public virtual product_variants product_variants { get; set; }
    }
}
