//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnLTWHQT
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public long id { get; set; }
        public long product_variant_id { get; set; }
        public long warehouse_id { get; set; }
        public int quantity_on_hand { get; set; }
        public int quantity_reserved { get; set; }
        public int reorder_level { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual product_variants product_variants { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}
