//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnLTWHQT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class perwEntities : DbContext
    {
        public perwEntities()
            : base("name=perwEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> addresses { get; set; }
        public virtual DbSet<branch_inventories> branch_inventories { get; set; }
        public virtual DbSet<branch> branches { get; set; }
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<discount> discounts { get; set; }
        public virtual DbSet<inbound_receipt_details> inbound_receipt_details { get; set; }
        public virtual DbSet<inbound_receipts> inbound_receipts { get; set; }
        public virtual DbSet<inventory> inventories { get; set; }
        public virtual DbSet<inventory_transactions> inventory_transactions { get; set; }
        public virtual DbSet<payment_methods> payment_methods { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<product_variants> product_variants { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<purchase_order_details> purchase_order_details { get; set; }
        public virtual DbSet<purchase_orders> purchase_orders { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<warehouse_transfer_details> warehouse_transfer_details { get; set; }
        public virtual DbSet<warehouse_transfers> warehouse_transfers { get; set; }
        public virtual DbSet<warehouse> warehouses { get; set; }
        public virtual DbSet<product_reviews> product_reviews { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<sp_BaoCaoTongTonKhoDonGian_Result> sp_BaoCaoTongTonKhoDonGian()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BaoCaoTongTonKhoDonGian_Result>("sp_BaoCaoTongTonKhoDonGian");
        }
    
        public virtual int sp_Branch_AddTransferRequestDetail(Nullable<long> transfer_id, Nullable<long> product_variant_id, Nullable<int> quantity, string notes)
        {
            var transfer_idParameter = transfer_id.HasValue ?
                new ObjectParameter("transfer_id", transfer_id) :
                new ObjectParameter("transfer_id", typeof(long));
    
            var product_variant_idParameter = product_variant_id.HasValue ?
                new ObjectParameter("product_variant_id", product_variant_id) :
                new ObjectParameter("product_variant_id", typeof(long));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            var notesParameter = notes != null ?
                new ObjectParameter("notes", notes) :
                new ObjectParameter("notes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Branch_AddTransferRequestDetail", transfer_idParameter, product_variant_idParameter, quantityParameter, notesParameter);
        }
    
        public virtual int sp_Branch_CreateTransferRequest(Nullable<long> from_warehouse_id, Nullable<long> to_branch_id, string notes, ObjectParameter new_transfer_id)
        {
            var from_warehouse_idParameter = from_warehouse_id.HasValue ?
                new ObjectParameter("from_warehouse_id", from_warehouse_id) :
                new ObjectParameter("from_warehouse_id", typeof(long));
    
            var to_branch_idParameter = to_branch_id.HasValue ?
                new ObjectParameter("to_branch_id", to_branch_id) :
                new ObjectParameter("to_branch_id", typeof(long));
    
            var notesParameter = notes != null ?
                new ObjectParameter("notes", notes) :
                new ObjectParameter("notes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Branch_CreateTransferRequest", from_warehouse_idParameter, to_branch_idParameter, notesParameter, new_transfer_id);
        }
    
        public virtual ObjectResult<sp_Branch_GetMyTransferRequests_Result> sp_Branch_GetMyTransferRequests(Nullable<long> branch_id)
        {
            var branch_idParameter = branch_id.HasValue ?
                new ObjectParameter("branch_id", branch_id) :
                new ObjectParameter("branch_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Branch_GetMyTransferRequests_Result>("sp_Branch_GetMyTransferRequests", branch_idParameter);
        }
    
        public virtual ObjectResult<sp_Branch_GetTransferRequestDetails_Result> sp_Branch_GetTransferRequestDetails(Nullable<long> transfer_id)
        {
            var transfer_idParameter = transfer_id.HasValue ?
                new ObjectParameter("transfer_id", transfer_id) :
                new ObjectParameter("transfer_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Branch_GetTransferRequestDetails_Result>("sp_Branch_GetTransferRequestDetails", transfer_idParameter);
        }
    
        public virtual int sp_CapNhatNguongDatHangLaiHangLoat(Nullable<int> nguongThap, Nullable<int> nguongMoi)
        {
            var nguongThapParameter = nguongThap.HasValue ?
                new ObjectParameter("NguongThap", nguongThap) :
                new ObjectParameter("NguongThap", typeof(int));
    
            var nguongMoiParameter = nguongMoi.HasValue ?
                new ObjectParameter("NguongMoi", nguongMoi) :
                new ObjectParameter("NguongMoi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatNguongDatHangLaiHangLoat", nguongThapParameter, nguongMoiParameter);
        }
    
        public virtual int sp_CreateBranch(string name, Nullable<long> warehouseID, string location, Nullable<long> managerUserID, ObjectParameter branchID, ObjectParameter success, ObjectParameter message)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var warehouseIDParameter = warehouseID.HasValue ?
                new ObjectParameter("WarehouseID", warehouseID) :
                new ObjectParameter("WarehouseID", typeof(long));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            var managerUserIDParameter = managerUserID.HasValue ?
                new ObjectParameter("ManagerUserID", managerUserID) :
                new ObjectParameter("ManagerUserID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CreateBranch", nameParameter, warehouseIDParameter, locationParameter, managerUserIDParameter, branchID, success, message);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_CreateProduct(string name, string slug, Nullable<long> categoryID, Nullable<long> supplierID, string description, string status, ObjectParameter productID, ObjectParameter success, ObjectParameter message)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var slugParameter = slug != null ?
                new ObjectParameter("Slug", slug) :
                new ObjectParameter("Slug", typeof(string));
    
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("CategoryID", categoryID) :
                new ObjectParameter("CategoryID", typeof(long));
    
            var supplierIDParameter = supplierID.HasValue ?
                new ObjectParameter("SupplierID", supplierID) :
                new ObjectParameter("SupplierID", typeof(long));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CreateProduct", nameParameter, slugParameter, categoryIDParameter, supplierIDParameter, descriptionParameter, statusParameter, productID, success, message);
        }
    
        public virtual int sp_DeleteProduct(Nullable<long> productID, ObjectParameter success, ObjectParameter message)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteProduct", productIDParameter, success, message);
        }
    
        public virtual int sp_DeleteProductVariant(Nullable<long> variantID, ObjectParameter success, ObjectParameter message)
        {
            var variantIDParameter = variantID.HasValue ?
                new ObjectParameter("VariantID", variantID) :
                new ObjectParameter("VariantID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteProductVariant", variantIDParameter, success, message);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_POS_Checkout_Classic(Nullable<long> branchID, Nullable<long> userID, Nullable<long> paymentMethodID)
        {
            var branchIDParameter = branchID.HasValue ?
                new ObjectParameter("BranchID", branchID) :
                new ObjectParameter("BranchID", typeof(long));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(long));
    
            var paymentMethodIDParameter = paymentMethodID.HasValue ?
                new ObjectParameter("PaymentMethodID", paymentMethodID) :
                new ObjectParameter("PaymentMethodID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_POS_Checkout_Classic", branchIDParameter, userIDParameter, paymentMethodIDParameter);
        }
    
        public virtual int sp_POS_Refund(Nullable<long> branchID, Nullable<long> originalOrderID, Nullable<long> variantID, Nullable<int> qty, string reason)
        {
            var branchIDParameter = branchID.HasValue ?
                new ObjectParameter("BranchID", branchID) :
                new ObjectParameter("BranchID", typeof(long));
    
            var originalOrderIDParameter = originalOrderID.HasValue ?
                new ObjectParameter("OriginalOrderID", originalOrderID) :
                new ObjectParameter("OriginalOrderID", typeof(long));
    
            var variantIDParameter = variantID.HasValue ?
                new ObjectParameter("VariantID", variantID) :
                new ObjectParameter("VariantID", typeof(long));
    
            var qtyParameter = qty.HasValue ?
                new ObjectParameter("Qty", qty) :
                new ObjectParameter("Qty", typeof(int));
    
            var reasonParameter = reason != null ?
                new ObjectParameter("Reason", reason) :
                new ObjectParameter("Reason", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_POS_Refund", branchIDParameter, originalOrderIDParameter, variantIDParameter, qtyParameter, reasonParameter);
        }
    
        public virtual int sp_ProcessTransferIssue(Nullable<long> branchID, Nullable<long> transferID, Nullable<long> variantID, Nullable<int> badQty, string note)
        {
            var branchIDParameter = branchID.HasValue ?
                new ObjectParameter("BranchID", branchID) :
                new ObjectParameter("BranchID", typeof(long));
    
            var transferIDParameter = transferID.HasValue ?
                new ObjectParameter("TransferID", transferID) :
                new ObjectParameter("TransferID", typeof(long));
    
            var variantIDParameter = variantID.HasValue ?
                new ObjectParameter("VariantID", variantID) :
                new ObjectParameter("VariantID", typeof(long));
    
            var badQtyParameter = badQty.HasValue ?
                new ObjectParameter("BadQty", badQty) :
                new ObjectParameter("BadQty", typeof(int));
    
            var noteParameter = note != null ?
                new ObjectParameter("Note", note) :
                new ObjectParameter("Note", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ProcessTransferIssue", branchIDParameter, transferIDParameter, variantIDParameter, badQtyParameter, noteParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_System_CreateSQLUser(string username, string password, string roleType)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var roleTypeParameter = roleType != null ?
                new ObjectParameter("RoleType", roleType) :
                new ObjectParameter("RoleType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_System_CreateSQLUser", usernameParameter, passwordParameter, roleTypeParameter);
        }
    
        public virtual int sp_TaoPhieuNhapHoanTraCN(Nullable<long> maChiNhanh, Nullable<long> maKhoDich, Nullable<long> maNguoiTao, Nullable<long> maBienThe, Nullable<int> soLuong, string ghiChu)
        {
            var maChiNhanhParameter = maChiNhanh.HasValue ?
                new ObjectParameter("MaChiNhanh", maChiNhanh) :
                new ObjectParameter("MaChiNhanh", typeof(long));
    
            var maKhoDichParameter = maKhoDich.HasValue ?
                new ObjectParameter("MaKhoDich", maKhoDich) :
                new ObjectParameter("MaKhoDich", typeof(long));
    
            var maNguoiTaoParameter = maNguoiTao.HasValue ?
                new ObjectParameter("MaNguoiTao", maNguoiTao) :
                new ObjectParameter("MaNguoiTao", typeof(long));
    
            var maBienTheParameter = maBienThe.HasValue ?
                new ObjectParameter("MaBienThe", maBienThe) :
                new ObjectParameter("MaBienThe", typeof(long));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaoPhieuNhapHoanTraCN", maChiNhanhParameter, maKhoDichParameter, maNguoiTaoParameter, maBienTheParameter, soLuongParameter, ghiChuParameter);
        }
    
        public virtual int sp_TaoPhieuNhapTuNCC(Nullable<long> maNCC, Nullable<long> maKho, Nullable<long> maNguoiTao, Nullable<long> maBienThe, Nullable<int> soLuong, Nullable<decimal> giaNhap)
        {
            var maNCCParameter = maNCC.HasValue ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(long));
    
            var maKhoParameter = maKho.HasValue ?
                new ObjectParameter("MaKho", maKho) :
                new ObjectParameter("MaKho", typeof(long));
    
            var maNguoiTaoParameter = maNguoiTao.HasValue ?
                new ObjectParameter("MaNguoiTao", maNguoiTao) :
                new ObjectParameter("MaNguoiTao", typeof(long));
    
            var maBienTheParameter = maBienThe.HasValue ?
                new ObjectParameter("MaBienThe", maBienThe) :
                new ObjectParameter("MaBienThe", typeof(long));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var giaNhapParameter = giaNhap.HasValue ?
                new ObjectParameter("GiaNhap", giaNhap) :
                new ObjectParameter("GiaNhap", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaoPhieuNhapTuNCC", maNCCParameter, maKhoParameter, maNguoiTaoParameter, maBienTheParameter, soLuongParameter, giaNhapParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int sp_Warehouse_AddTransferDetail(Nullable<long> transfer_id, Nullable<long> product_variant_id, Nullable<int> quantity, string notes)
        {
            var transfer_idParameter = transfer_id.HasValue ?
                new ObjectParameter("transfer_id", transfer_id) :
                new ObjectParameter("transfer_id", typeof(long));
    
            var product_variant_idParameter = product_variant_id.HasValue ?
                new ObjectParameter("product_variant_id", product_variant_id) :
                new ObjectParameter("product_variant_id", typeof(long));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            var notesParameter = notes != null ?
                new ObjectParameter("notes", notes) :
                new ObjectParameter("notes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Warehouse_AddTransferDetail", transfer_idParameter, product_variant_idParameter, quantityParameter, notesParameter);
        }
    
        public virtual int sp_Warehouse_ApproveTransfer(Nullable<long> transfer_id, string notes)
        {
            var transfer_idParameter = transfer_id.HasValue ?
                new ObjectParameter("transfer_id", transfer_id) :
                new ObjectParameter("transfer_id", typeof(long));
    
            var notesParameter = notes != null ?
                new ObjectParameter("notes", notes) :
                new ObjectParameter("notes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Warehouse_ApproveTransfer", transfer_idParameter, notesParameter);
        }
    
        public virtual int sp_Warehouse_CompleteTransfer(Nullable<long> transfer_id, string notes)
        {
            var transfer_idParameter = transfer_id.HasValue ?
                new ObjectParameter("transfer_id", transfer_id) :
                new ObjectParameter("transfer_id", typeof(long));
    
            var notesParameter = notes != null ?
                new ObjectParameter("notes", notes) :
                new ObjectParameter("notes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Warehouse_CompleteTransfer", transfer_idParameter, notesParameter);
        }
    
        public virtual int sp_Warehouse_CreateTransfer(Nullable<long> from_warehouse_id, Nullable<long> to_branch_id, string status, string notes, ObjectParameter new_transfer_id)
        {
            var from_warehouse_idParameter = from_warehouse_id.HasValue ?
                new ObjectParameter("from_warehouse_id", from_warehouse_id) :
                new ObjectParameter("from_warehouse_id", typeof(long));
    
            var to_branch_idParameter = to_branch_id.HasValue ?
                new ObjectParameter("to_branch_id", to_branch_id) :
                new ObjectParameter("to_branch_id", typeof(long));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var notesParameter = notes != null ?
                new ObjectParameter("notes", notes) :
                new ObjectParameter("notes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Warehouse_CreateTransfer", from_warehouse_idParameter, to_branch_idParameter, statusParameter, notesParameter, new_transfer_id);
        }
    
        public virtual ObjectResult<sp_Warehouse_GetAllTransfers_Result> sp_Warehouse_GetAllTransfers(Nullable<long> warehouse_id, string status)
        {
            var warehouse_idParameter = warehouse_id.HasValue ?
                new ObjectParameter("warehouse_id", warehouse_id) :
                new ObjectParameter("warehouse_id", typeof(long));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Warehouse_GetAllTransfers_Result>("sp_Warehouse_GetAllTransfers", warehouse_idParameter, statusParameter);
        }
    
        public virtual ObjectResult<sp_Warehouse_GetTransferDetails_Result> sp_Warehouse_GetTransferDetails(Nullable<long> transfer_id)
        {
            var transfer_idParameter = transfer_id.HasValue ?
                new ObjectParameter("transfer_id", transfer_id) :
                new ObjectParameter("transfer_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Warehouse_GetTransferDetails_Result>("sp_Warehouse_GetTransferDetails", transfer_idParameter);
        }
    
        public virtual int sp_Warehouse_RejectTransfer(Nullable<long> transfer_id, string reason)
        {
            var transfer_idParameter = transfer_id.HasValue ?
                new ObjectParameter("transfer_id", transfer_id) :
                new ObjectParameter("transfer_id", typeof(long));
    
            var reasonParameter = reason != null ?
                new ObjectParameter("reason", reason) :
                new ObjectParameter("reason", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Warehouse_RejectTransfer", transfer_idParameter, reasonParameter);
        }
    
        public virtual int sp_Warehouse_UpdateTransferStatus(Nullable<long> transfer_id, string new_status, string notes)
        {
            var transfer_idParameter = transfer_id.HasValue ?
                new ObjectParameter("transfer_id", transfer_id) :
                new ObjectParameter("transfer_id", typeof(long));
    
            var new_statusParameter = new_status != null ?
                new ObjectParameter("new_status", new_status) :
                new ObjectParameter("new_status", typeof(string));
    
            var notesParameter = notes != null ?
                new ObjectParameter("notes", notes) :
                new ObjectParameter("notes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Warehouse_UpdateTransferStatus", transfer_idParameter, new_statusParameter, notesParameter);
        }
    
        public virtual int sp_XuatKhoChiNhanh(Nullable<long> maBienThe, Nullable<long> maKhoTong, Nullable<long> maChiNhanh, Nullable<int> soLuong)
        {
            var maBienTheParameter = maBienThe.HasValue ?
                new ObjectParameter("MaBienThe", maBienThe) :
                new ObjectParameter("MaBienThe", typeof(long));
    
            var maKhoTongParameter = maKhoTong.HasValue ?
                new ObjectParameter("MaKhoTong", maKhoTong) :
                new ObjectParameter("MaKhoTong", typeof(long));
    
            var maChiNhanhParameter = maChiNhanh.HasValue ?
                new ObjectParameter("MaChiNhanh", maChiNhanh) :
                new ObjectParameter("MaChiNhanh", typeof(long));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XuatKhoChiNhanh", maBienTheParameter, maKhoTongParameter, maChiNhanhParameter, soLuongParameter);
        }
    
        public virtual int sp_XuatKhoTheoDonHang(Nullable<long> maDonHang, Nullable<long> maKho)
        {
            var maDonHangParameter = maDonHang.HasValue ?
                new ObjectParameter("MaDonHang", maDonHang) :
                new ObjectParameter("MaDonHang", typeof(long));
    
            var maKhoParameter = maKho.HasValue ?
                new ObjectParameter("MaKho", maKho) :
                new ObjectParameter("MaKho", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XuatKhoTheoDonHang", maDonHangParameter, maKhoParameter);
        }
    }
}
