//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnLTWHQT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class perwEntities : DbContext
    {
        public perwEntities()
            : base("name=perwEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> addresses { get; set; }
        public virtual DbSet<branch_inventories> branch_inventories { get; set; }
        public virtual DbSet<branch> branches { get; set; }
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<inbound_receipt_details> inbound_receipt_details { get; set; }
        public virtual DbSet<inbound_receipts> inbound_receipts { get; set; }
        public virtual DbSet<inventory> inventories { get; set; }
        public virtual DbSet<inventory_transactions> inventory_transactions { get; set; }
        public virtual DbSet<payment_methods> payment_methods { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<product_variants> product_variants { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<purchase_order_details> purchase_order_details { get; set; }
        public virtual DbSet<purchase_orders> purchase_orders { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<warehouse_transfer_details> warehouse_transfer_details { get; set; }
        public virtual DbSet<warehouse_transfers> warehouse_transfers { get; set; }
        public virtual DbSet<warehouse> warehouses { get; set; }
        public virtual DbSet<product_reviews> product_reviews { get; set; }
        public virtual DbSet<discount> discounts { get; set; }
    }
}
