//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnLTWHQT
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public purchase_orders()
        {
            this.inventory_transactions = new HashSet<inventory_transactions>();
            this.payments = new HashSet<payment>();
            this.purchase_order_details = new HashSet<purchase_order_details>();
        }
    
        public long id { get; set; }
        public Nullable<long> user_id { get; set; }
        public string order_code { get; set; }
        public string status { get; set; }
        public string shipping_recipient_name { get; set; }
        public string shipping_recipient_phone { get; set; }
        public string shipping_address { get; set; }
        public decimal sub_total { get; set; }
        public decimal shipping_fee { get; set; }
        public decimal discount_amount { get; set; }
        public decimal total_amount { get; set; }
        public Nullable<long> discount_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual discount discount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory_transactions> inventory_transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment> payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_order_details> purchase_order_details { get; set; }
        public virtual user user { get; set; }
    }
}
