//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnLTWHQT
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse_transfer_details
    {
        public long id { get; set; }
        public long transfer_id { get; set; }
        public long product_variant_id { get; set; }
        public int quantity { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual product_variants product_variants { get; set; }
        public virtual warehouse_transfers warehouse_transfers { get; set; }
    }
}
