//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnLTWHQT
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public long id { get; set; }
        public long user_id { get; set; }
        public string recipient_name { get; set; }
        public string recipient_phone { get; set; }
        public string street_address { get; set; }
        public string ward { get; set; }
        public string district { get; set; }
        public string city { get; set; }
        public bool is_default { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual user user { get; set; }
    }
}
